### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by n4uti** [FlyersWeb/angular-symfony#11]
I noticed that after the login the session lifetime is endless so the user will not be logged out after a specific idle time. I think this should be managed at client side because the rest endpoints are stateless and there is no server managed session. Do you have some ides for managing this? Could you help me out there? Thanks for this cool framework, n4uti.

**Comment by n4uti** [comment]
I think we also have to clear the session if the user closes the browser or request another page. It would be a nice security feature.

**Comment by rodolfobandeira** [comment]
Hi @n4uti 
Did you try to change the lifetime values? It shows up in two places, check this out:
https://github.com/FlyersWeb/angular-symfony/search?utf8=%E2%9C%93&q=lifetime&type=Code

**Comment by n4uti** [comment]
Hi, this is just the lifetime for the nonce... 
Here are more details:

https://github.com/FlyersWeb/angular-symfony/issues/9

**Comment by FlyersWeb** [comment]
This could be counter productive in some cases, for example you don't want to logout a user on page change for example if he clicks on a bad link and want to come back.
Actually I've never seen a website with this feature. I don't think it will be implemented without more arguments, maybe I'm wrong ?
