### ISSUE TITLE
MAMP

### ISSUE THREAD

**Issue by zsala** [FlyersWeb/angular-symfony#15]
I cloned the repository into /htdocs using MAMP. If I go through the commands listed in the readme I get the following errors:

1. Going to _http://localhost:8888/angular-symfony/web/#/login_ or _http://localhost:8888/angular-symfony/web/app_dev.php/#/login_ the js does not find the templates.
2. Playing around with the paths in app.js I will get /username/salt not defined.
3. Which symfony2 version do u used? "SecurityContextInterface" is deprecated at me (See WsseListener) UPDATE: version 2.6.x cleares this problem.

Do I missed some setup step?
U.I Symfony2 version 2.7.10

**Comment by FlyersWeb** [comment]
Hi, do you have mod_rewrite enabled? You should access the project using http://localhost:8888/angular-symfony/ (no web).
To install dependencies (with symfony) you should use composer.phar install

**Comment by FlyersWeb** [comment]
I personally use a virtualhost for my testings, let me try with a subfolder to see if I get the problem

**Comment by FlyersWeb** [comment]
Issue should have been resolved with commit 752adc86400fa5e318da4d57d195f7ac04fe3722. Let me know if it's OK now.
