### ISSUE TITLE
Encoders setting in security.yml

### ISSUE THREAD

**Issue by micguo** [FlyersWeb/angular-symfony#16]
For some reason, I had a hard time getting php and js side encoders agree to each other.

After change
`security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512`
to
`security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000`

Things start to work.

I think my symfony default setting somehow screwed up. But maybe it is a good idea to not rely on default setting and set the encoder details in security.yml.

Just want to highlight the issue I got, maybe helpful to others.

PS: Thanks for this project!

**Comment by FlyersWeb** [comment]
Thanks, will add it to the README
