### ISSUE TITLE
Subdirectory issue in routing

### ISSUE THREAD

**Issue by kbzowski** [FlyersWeb/angular-symfony#19]
It looks like templateUrl in app.js does not recognize that the page is located in subdirectory.
I made an alias in Apache config to directory where my application is being developed:

`Alias "/mysite" "E:/work/mysite/web"`
`<Directory "E:/work/mysite/web">`
`     Options FollowSymLinks Indexes`
`     AllowOverride All`
`</Directory>`
But when I visit http://127.0.0.1/mysite firebug reports 404 error because script want to access http://127.0.0.1/bundles/app/partials/login.html which is wrong, because login.html should be accessed using http://127.0.0.1/mysite/bundles/app/partials/login.html

Was it intended? Do I have to enter prefix to the angular routing by myself?

**Comment by FlyersWeb** [comment]
Issue will be corrected after branch [separated.concerns.refactoring](https://github.com/FlyersWeb/angular-symfony/tree/separated.concerns.refactoring) is finished and merged.

**Comment by FlyersWeb** [comment]
corrected by merge f189afe62def2a6eb32fc1c3ee19074748baea22
