### ISSUE TITLE
CrytoJS doesn't exist

### ISSUE THREAD

**Issue by fofiedelly** [FlyersWeb/angular-symfony#20]
HI @all,

googlecode.com is returning a 404 for all crytojs files. 

Is it a known issue?? 

Regards!

**Comment by FlyersWeb** [comment]
Hi,

Thanks for the message, and yes it's a known issue, the library as changed path.

I'm working on it in the separated.concerns.refactoring. It should be resolved when merged.

Best regards

**Comment by fofiedelly** [comment]
Okay nice. 
I take a look at it. 
Regards.

**Comment by FlyersWeb** [comment]
Corrected by merge f189afe62def2a6eb32fc1c3ee19074748baea22
