### ISSUE TITLE
Purpose of using express

### ISSUE THREAD

**Issue by kbzowski** [FlyersWeb/angular-symfony#21]
What was the purpose of using express for serving front-end? That additional layer appears to be unnecessary. Why front-end cannot be serve directly using httpd server?

**Comment by mappedinn** [comment]
:+1:

**Comment by FlyersWeb** [comment]
The purpose to use express was for the boilerplate only, you could serve statics as you want. But because express is application side, I am sure it works on all node compatible machines ;)
Regards.
