### ISSUE TITLE
Another authentication needed after page reload

### ISSUE THREAD

**Issue by rynqu** [FlyersWeb/angular-symfony#6]
The app remains authenticated until page gets reloaded. After reload, the user has to be authenticated again.

**Comment by FlyersWeb** [comment]
Information should be stored in cookie for refresh management. Will work on it when I have some times.

**Comment by FlyersWeb** [comment]
Corrected by commit a93d85b4c0f7ca75f8d1b2f4fe9424465a2ff326.

**Comment by atulmy** [comment]
This is great! \m/ \m/
