### ISSUE TITLE
App performs http requests that are sure to get 403 response

### ISSUE THREAD

**Issue by rynqu** [FlyersWeb/angular-symfony#8]
In controller.js there should be return; statements after all $window.location = '#/login'; .Otherwise, the app will perform requests to secure urls for user, that is not even authenticated, which will result in 403 response.
PS. Guys, thank you for your work! :) It's very useful pice of code!

**Comment by FlyersWeb** [comment]
Thanks for the issue, and I'm happy it helped you.
Will work on that ASAP

**Comment by FlyersWeb** [comment]
Corrected by commit b6d4333186a5940ec3161b5efe72a220dd4072d0.
