### ISSUE TITLE
Nonce seed

### ISSUE THREAD

**Issue by n4uti** [FlyersWeb/angular-symfony#9]
While using Math.floor( Math.random() * 1000 ) to calculate the seed for the next nonce i recognized a problem:

Math.floor( Math.random() * 1000 )
282
Math.floor( Math.random() * 1000 )
979
Math.floor( Math.random() * 1000 )
396
Math.floor( Math.random() * 1000 )
396

In fact its possible that the seed function returns the same value as before so the nonce calculation would result in the same string as before. The WsseProvider would throw new NonceExpiredException('Previously used nonce detected') and the WsseListener would catch this Exception and return a plain message to the client. This could also result in client JSON errors while it is expecting JSON data.

I would suggest to calculate the nonce string this way:

        tokenHandler.randomString = function(length) {
            var text = "";
            var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            for(var i = 0; i < length; i++) {
                text += possible.charAt(Math.floor(Math.random() * possible.length));
            }
            return text;
        }

var nonce = tokenHandler.randomString(30);
var created = formatDate(new Date());
var hash = CryptoJS.SHA1(nonce + created + secret);
var digest = hash.toString(CryptoJS.enc.Base64);
var b64nonce = Base64.encode(nonce);
return 'UsernameToken Username="' + username + '", PasswordDigest="' + digest + '", Nonce="' + b64nonce + '", Created="' + created + '"';

Of course there are many ways to calculate, so this is only one suggestion provided by:
https://blog.nraboy.com/2015/03/create-a-random-nonce-string-using-javascript/

Thanks for the great work. Looking forward to see some solution for handling "session timeout" after idling some time to tell the client that the cookie data will be purged and the user has to login again.

**Comment by davidbonachera** [comment]
This is a better way to generate the nonce, thanks for this function, very usefull :+1:

**Comment by FlyersWeb** [comment]
Hi,

Actually you're totally right, there is a collision risk while generating nonce using random + md5.

Actually to be sure to have a more random nonce generator, it is possible to use random.org API service.

But we have to remember that nonce has a lifetime of 300 seconds so this risk is limited.

Thanks to notice that, I'll correct that nonce generation when I get a moment, you can also make a pull request if you want :)

See you.

**Comment by FlyersWeb** [comment]
Corrected by d26b461
